<?php

 function linnotest_menu() {
   $items = array();
    $items['cars'] = array(
        'title' => t('list of cars'), // can actually be arbitrary text here
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'mymodule_cars_view',
        'access callback' => TRUE,
    );
    return $items;
  }

 function mymodule_cars_view(){





   	$result = db_query("SELECT *
    FROM node AS n
    LEFT JOIN field_data_field_imagecar c ON n.nid = c.entity_id
    LEFT JOIN file_managed f ON f.fid = c.field_imagecar_fid
    WHERE type = 'car'
    ")->fetchAll();
        drupal_json_output( $result);
      }



  /**
 * Implements hook_block_info().
 */
function linnotest_block_info() {
  $blocks = array();
  $blocks['cars'] = array(
    'info' => t('Cars Block'),
  );

  return $blocks;
}

function linnotest_block_view($delta = '') {
  if($delta == 'cars')
      $block['content'] = list_cars();
  return $block;
}

function list_cars() {
  $output = '<script type="text/javascript" src="/angular/angular-min.js"></script>';
  $output .= '<script type="text/javascript" src="/angular/cars.js"></script>';
  $output .= <<<HTML
    <div ng-app="myApp">
    <div ng-controller = "getCars">

    <input type="search" ng-model="carl" placeholder="filter car..." />
    <ul class="list-cars">
    <li class="animate-repeat" ng-repeat="car in cars" | filter:carl | getimg:car.uri>
<img src = "sites/linnotest.localhost/files/{{car.filename}}" style="
    width: 200px;
    height: 100px;
">
     <a href = "/node/{{car.nid}}">{{car.title}}</a>
    </li>
  </ul>

     
   </div>
  </div>
HTML;
    return $output;
}